### ISSUE TITLE
Add Export/Save/Link functionality

### ISSUE THREAD

**Issue by kevinreedy** [88mpg/shuffleboard#2]
I had a thought for a good way to share/save data with the tool:
 - [ ] Add a button to "Share"
 - [ ] This button will embed the x/y coords in url/`window.location` and give users an easy button to copy the url to clipboard
 - [ ] On load, update biscuit positions based on the get data

I'll try to get this working in the next week or two as a way to get familiar with the code!

**Comment by 88mpg** [comment]
@kevinreedy that's an awesome idea! code shouldn't be too hard to digest. if you're interested in contributing that could definitely motivate @Iaaan and myself to put some more work into this project.

**Comment by 88mpg** [comment]
This feature is already built and stable in the new version! Currently being built in private. You have access to the private repo FYI 😉
