### ISSUE TITLE
Add Drift Line

### ISSUE THREAD

**Issue by kevinreedy** [88mpg/shuffleboard#3]
I just thought of another interesting feature (that I'll try to crank out when I have some time on a weekend)! It'd be great to have a button you can tap and then draw a line to show the approximate drift of the court.

**Comment by 88mpg** [comment]
New version currently being built from scratch already has the ability to draw a line on drag, but right now it's only being used to outline biscuit movement.

I've got a couple things on my list before I get to this but it'd be pretty neat, maybe when enabled a gradient/gradients generated underneath the court on drag?
